### ISSUE TITLE
AssemblyScript could be faster with `-O3`

### ISSUE THREAD

**Issue by MaxGraey** [alamusi/wa-test#1]
if change from `--optimize` to `-O3` [here](https://github.com/alamusi/wa-test/blob/master/package.json#L8). It should speedup AssemblyScript native math even more due to using more performant algorithm but more larger in term of code size.

**Comment by alamusi** [comment]
@MaxGraey thanks for the suggestion! 

Now there are three builds to compare `-O`, `-O3`, and `-O3z` with the latest commit (https://github.com/alamusi/wa-test/commit/b0818f1ba6c9e2e9fd6f5bf15a716bfd1fe07191). The build sizes of `-O` and `-O3z` are almost same. Presumably the default optimization in this case is towards size. The `-O3` build shows good improvement on the math calculation. 

The code size is normally a huge concern, so long it doesn't translate to significant memory consumption in more complex scenarios (which I didn't see a huge difference in this simple test).

**Comment by MaxGraey** [comment]
> The build sizes of -O and -O3z are almost same

Yes, that's true `-O3s` / `-O` and `-O3z` usually the same. But `-O3z` in some cases could be smaller.

> The -O3 build shows good improvement on the math calculation.

Great! Thanks!
